<?php

namespace Tests\Feature;

use App\Models\Property;
use App\Models\PropertyContract;
use App\Models\User;
use App\Services\PaymentGeneratorService;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PropertyPaymentRescheduleTest extends TestCase
{
    use RefreshDatabase;

    protected PaymentGeneratorService $service;

    protected User $superAdmin;

    protected Property $property;

    protected User $owner;

    protected function setUp(): void
    {
        parent::setUp();

        $this->superAdmin = User::factory()->create(['type' => 'super_admin']);
        $this->actingAs($this->superAdmin);

        $this->service = app(PaymentGeneratorService::class);

        $this->owner = User::factory()->create(['type' => 'owner']);
        $this->property = Property::factory()->create(['owner_id' => $this->owner->id]);
    }

    private function createPropertyContractWithPayments(
        int $months,
        string $frequency,
        int $paidCount = 0,
        float $commissionRate = 5.0
    ): PropertyContract {
        $contract = PropertyContract::create([
            'contract_number' => 'PC-TEST-'.rand(1000, 9999),
            'owner_id' => $this->owner->id,
            'property_id' => $this->property->id,
            'commission_rate' => $commissionRate,
            'duration_months' => $months,
            'start_date' => Carbon::now()->startOfMonth(),
            'end_date' => Carbon::now()->startOfMonth()->addMonths($months)->subDay(),
            'payment_frequency' => $frequency,
            'contract_status' => 'active',
        ]);

        // Note: Payments are auto-generated by PropertyContractObserver

        // Mark some as paid
        $payments = $contract->supplyPayments()->orderBy('due_date')->get();
        for ($i = 0; $i < $paidCount && $i < count($payments); $i++) {
            $payments[$i]->update([
                'paid_date' => Carbon::now(),
            ]);
        }

        return $contract->fresh();
    }

    /** test  اعاده جدوله عقد العقارات*/
    public function test_property_reschedule_extends_duration()
    {
        $contract = $this->createPropertyContractWithPayments(12, 'quarterly', 1); // 4 payments, 1 paid

        $result = $this->service->reschedulePropertyContractPayments(
            $contract,
            10.0, // New commission
            12,   // Add 12 months
            'quarterly'
        );

        $this->assertEquals(3, $result['deleted_count']); // 4 total - 1 paid = 3 unpaid deleted
        $this->assertCount(4, $result['new_payments']); // 12 months / quarterly = 4 new

        $contract->refresh();
        $this->assertEquals(10.0, $contract->commission_rate);
        $this->assertEquals(15, $contract->duration_months); // 3 paid months + 12 new
    }

    /** test  تغيير عدد مرات الدفع */
    public function test_property_reschedule_changes_frequency()
    {
        $contract = $this->createPropertyContractWithPayments(12, 'monthly', 6); // 12 payments, 6 paid

        $result = $this->service->reschedulePropertyContractPayments(
            $contract,
            5.0,
            6, // Add 6 months
            'quarterly'
        );

        $this->assertEquals(6, $result['deleted_count']);
        $this->assertCount(2, $result['new_payments']); // 6 months / quarterly = 2 new

        $contract->refresh();
        $this->assertEquals('quarterly', $contract->payment_frequency);
        $this->assertEquals(12, $contract->duration_months); // 6 paid months + 6 new
    }

    /** test  تراجع في عملية إعادة جدول الدفع */
    public function test_property_reschedule_rollback_on_failure()
    {
        $contract = $this->createPropertyContractWithPayments(12, 'monthly', 3);
        $countBefore = $contract->supplyPayments()->count();

        try {
            $this->service->reschedulePropertyContractPayments(
                $contract,
                150.0, // Invalid commission > 100
                6,
                'monthly'
            );
        } catch (\InvalidArgumentException $e) {
            // Expected
        }

        $contract->refresh();
        $this->assertEquals($countBefore, $contract->supplyPayments()->count());
        $this->assertEquals(12, $contract->duration_months);
    }
}
